### ISSUE TITLE
Crash/freeze

### ISSUE THREAD

**Issue by beeperson** [rickyminecraft/prispongemine#1]
When i use the /fill [name] Command it freezes the console, the players time out, and the console will not execute any more commands or run properly, to my best guess it would be my ram issue as i am local hosting with minimal ram, (3GB) i created a small mine consisting of many blocks as it will be a (material) mine, /clear [name] works perfectly but when i go to fill i run into this issue Please let me know if you need my config file or anything else,

**Comment by beeperson** [comment]
http://pastebin.com/jJxS8J81

**Comment by JamieS1211** [comment]
Try using a version after or including "PrispongeMine 1.1"

**Comment by rickyminecraft** [comment]
Yes, i think you use version 1.0.6 or below, use version 1.1 or newer.

**Comment by rickyminecraft** [comment]
without response i consider this closed.

**Comment by beeperson** [comment]
Sorry for the Delay i have been without Internet, This has been fixed with an update thanks for the response and help
